### Necessário para pegar o token    
### Post  
# @name loginAutenticado  
POST http://localhost:40000/Login HTTP/1.1  
content-type: application/json  
  
{      
    "UserName": "qwe",  
    "Password": "qwe"  
}  
### Seta o token  
@accessToken = {{loginAutenticado.response.body.$.token}}  
@username = {{loginAutenticado.response.body.$.username}}  


### teste de buscar todos os alunos  
GET http://localhost:40000/GetAllClientes HTTP/1.1  
content-type: application/json  
Authorization: Bearer {{accessToken}}  

{      
    
}  

### teste de buscar cliente por ID  
POST http://localhost:40000/GetClienteByID HTTP/1.1  
content-type: application/json  
//Authorization:  {{accessToken}}  

{     
    "cursoid": 4  
}  

### teste de inserção de cliente  
POST http://localhost:40000/InsertClientes HTTP/1.1  
content-type: application/json  
//Authorization: Bearer  
 eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzM0ODE2NDEsInVzZXJuYW1lIjoicXdlIn0.LRKs8uvt-SJ9E9dMGYRkCs7HhMDlqVmwap_zcaoONeQ  
  
{      
    "clienteid": 0,  
    "documento": "91993847374",   
    "nomeRazaoSocial": "Rogerio",  
    "email": "Rogerio@gmail.com",  
    "ativo": true      
}  

### teste de atualização de aluno  
POST http://localhost:40000/UpdateClientes HTTP/1.1  
content-type: application/json  
//Authorization: Bearer  
 eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzM0ODE2NDEsInVzZXJuYW1lIjoicXdlIn0.LRKs8uvt-SJ9E9dMGYRkCs7HhMDlqVmwap_zcaoONeQ  

{      
    "clienteid": 2,  
    "documento": "99988889999",  
    "nomeRazaoSocial": "Roberto",  
    "email": "rh@gmail.com",  
    "ativo": true   
}  

### teste de atualização de aluno  
POST http://localhost:40000/DeleteClientes HTTP/1.1  
content-type: application/json  
//Authorization: Bearer  
 eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzM0ODE2NDEsInVzZXJuYW1lIjoicXdlIn0.LRKs8uvt-SJ9E9dMGYRkCs7HhMDlqVmwap_zcaoONeQ  

{      
    "clienteid": 2    
}  
